### ISSUE TITLE
Hello World does not run

### ISSUE THREAD

**Issue by weikai77** [digitalbazaar/bedrock-hello-world#3]
$ npm start

> bedrock-hello-world@0.0.0 start /Users/kwei/bedrock/bedrock-hello-world
> node helloworld.js

/Users/kwei/bedrock/bedrock-hello-world/node_modules/bedrock/lib/bedrock.js:40
  'paths.cache': () => {
                  ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kwei/bedrock/bedrock-hello-world/helloworld.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by mattcollier** [comment]
@weikai77 Sorry, this package is not being maintained.  We might fix it up, meanwhile you can find good examples in https://github.com/digitalbazaar/bedrock-examples

If you tell me what you're interested in (front end/back end) I can recommend an example for you to try.
